/**
 * Tool to generate the api client.
 *
 * Authored by Jacob Humston
 */
import openapiTS, { astToString } from 'openapi-typescript';

import { readFileSync, writeFileSync } from 'node:fs';

const header = (name: string) => `/**
 * Types for the ${name}, generated in 'tools/update-api-types.ts'.
 *
 * Generated by https://openapi-ts.dev/
 */\n`;

// api client
try {
    // port 80 should be good for dev
    const api = await openapiTS(new URL('http://localhost:80/api/spec'));
    writeFileSync('src/shared/api-types.ts', header('API client') + astToString(api));
} catch (e) {
    console.log(e);
}

// printful api
try {
    // port 80 should be good for dev
    const v1 = await openapiTS(readFileSync('src/server/apis/printful/v1.json'));
    const v2 = await openapiTS(readFileSync('src/server/apis/printful/v2.json'));
    writeFileSync(
        'src/server/apis/printful/types.ts',
        header('printful API client') +
            `export namespace v1 { ${astToString(v1)} } export namespace v2 { ${astToString(v2)} }`
    );
} catch (e) {
    console.log(e);
}

console.log('Done!');
