/**
 * Tool to generate the api client.
 *
 * Authored by Jacob Humston
 */
import openapiTS, { astToString } from 'openapi-typescript';

import { writeFileSync } from 'node:fs';

const header = `/**
 * Types for the API client, generated in 'tools/update-api-types.ts'.
 *
 * Generated by https://openapi-ts.dev/
 */\n`;

// port 80 should be good for dev
const api = await openapiTS(new URL('http://localhost:80/api/spec'));
writeFileSync('src/shared/api-types.ts', header + astToString(api));

console.log('Updated!');
